# Stage: 0
FROM cgr.dev/chainguard/go:latest as build
ENV APP_HOME=/app
RUN useradd -m -s /bin/bash -d $APP_HOME myappuser
WORKDIR $APP_HOME
COPY go.mod go.sum $APP_HOME/
RUN apt-get update \
    && apt-get clean \
    && go mod download
COPY src/ $APP_HOME/src/
RUN CGO_ENABLED=0 go build -o myapp $APP_HOME/src/main.go

# Stage: 1
FROM cgr.dev/chainguard/static:latest
ENV APP_USER=myappuser
ENV APP_HOME=/app
RUN useradd -m -s /bin/bash -d $APP_HOME $APP_USER
WORKDIR $APP_HOME
COPY --chown=65532:65532 --from=build  $APP_HOME/myapp $APP_HOME/myapp
USER $APP_USER
CMD ["./myapp"]

