# Stage: 0
FROM cgr.dev/chainguard/clang:latest as build
WORKDIR $APP_HOME
ENV APP_HOME=/app
COPY src/ $APP_HOME/src/
COPY Makefile $APP_HOME/
RUN apt-get update \
    && apt-get install -y gcc \
    && apt-get clean \
    && useradd -m -s /bin/bash -d $APP_HOME myappuser
RUN make -C $APP_HOME

# Stage: 1
FROM cgr.dev/chainguard/static:latest
WORKDIR $APP_HOME
ENV APP_USER=myappuser
ENV APP_HOME=/app
USER $APP_USER
COPY --chown=65532:65532 --from=build  $APP_HOME/src/myapp $APP_HOME/src/myapp
RUN useradd -m -s /bin/bash -d $APP_HOME $APP_USER
CMD ["./src/myapp"]

