# Stage: 0
FROM cgr.dev/chainguard/go:latest as build
ENV APP_HOME=/app
WORKDIR $APP_HOME
COPY src/ $APP_HOME/src/
RUN CGO_ENABLED=0 go build -o myapp $APP_HOME/src/main.go

# Stage: 1
FROM cgr.dev/chainguard/static:latest
ENV APP_USER=myappuser
ENV APP_HOME=/app
WORKDIR $APP_HOME
USER $APP_USER
COPY --chown=65532:65532 --from=build  $APP_HOME/myapp $APP_HOME/myapp
RUN useradd -m -s /bin/bash -d $APP_HOME $APP_USER
CMD ["./myapp"]

