# Stage: 0
FROM cgr.dev/chainguard/go:latest as build
WORKDIR $APP_HOME
ENV APP_HOME=/app
COPY go.mod go.sum $APP_HOME/
COPY src/ $APP_HOME/src/
RUN useradd -m -s /bin/bash -d $APP_HOME myappuser
RUN apt-get update \
    && apt-get clean \
    && go mod download
RUN CGO_ENABLED=0 go build -o myapp $APP_HOME/src/main.go

# Stage: 1
FROM cgr.dev/chainguard/static:latest
WORKDIR $APP_HOME
ENV APP_USER=myappuser
ENV APP_HOME=/app
USER $APP_USER
COPY --chown=65532:65532 --from=build  $APP_HOME/myapp $APP_HOME/myapp
RUN useradd -m -s /bin/bash -d $APP_HOME $APP_USER
CMD ["./myapp"]

